# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2230d53a852a27a45d377811a92df20079cb86d7f692eebc643f60741b6abff6aeb5a47ad8576e3273c288818b1b2ebb9c8ef7830e0f7e811a034b167a17310f

test:
  secret_key_base: fd51a728f3c91b70d8d786d6265a9e2dec30c414d2121edd38bbf9f6abe82e09eb86441024e7cb695ca02742c960ecf03d60e4b3db9f9d23e68339199923da3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
